### ISSUE TITLE
Compatibility warning with AMS 7.5 and AMMR 2.5

### ISSUE THREAD

**Issue by depierie** [AnyBody/anyknee#1]
ERROR(OBJ.MCH.SURF4) :   Femur_FitCylinders.any(33)  :   test_cylinder_fit  :  Deprecated use of AnySurf*Fit classes identified. Compatibility mode entered. 
 1) Use new concept by remove initializations of sRel and ARel (Recommended). 
 2) Read the long error description to see how to maintain backwards compatibility of your model.

**Comment by melund** [comment]
Fixed by #2
